### ISSUE TITLE
Android - NullPointerException in SplashScreen.run (version 5.0.3)

### ISSUE THREAD

**Issue by chuchuva** [apache/cordova-plugin-splashscreen#298]
### What is expected to happen?
No crash

### What does actually happen?
App crashes on startup. 

## Information
It happens very rarely. I can see it in bug reports. Unfortunately I can't reproduce it locally.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAnimation(android.view.animation.Animation)' on a null object reference
    at org.apache.cordova.splashscreen.SplashScreen$4.run(SplashScreen.java:230)
    at android.app.Activity.runOnUiThread(Activity.java:6388)
    at org.apache.cordova.splashscreen.SplashScreen.removeSplashScreen(SplashScreen.java:220)
    at org.apache.cordova.splashscreen.SplashScreen.access$1000(SplashScreen.java:50)
    at org.apache.cordova.splashscreen.SplashScreen$5$1.run(SplashScreen.java:337)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6971)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

### Environment, Platform, Device
Samsung Chromebook Plus (V2)
screen_resolution: "1541x1043",
model_id: "R85-13310.93.0",
low_memory: false,
orientation: "portrait",
family: "Samsung",
battery_level: 58.999996,
type: "device",
brand: "google",
simulator: false,
free_storage: 29528276992,
storage_size: 51982630912,
screen_dpi: 213,
free_memory: 1558048768,
memory_size: 4030775296,
online: true,
model: "Samsung Chromebook Plus (V2)",
screen_density: 1.3312501,
arch: "x86_64",
charging: false,
manufacturer: "Google"

### Version information

cordova-plugin-splashscreen: version 5.0.3

Ionic:

   Ionic CLI                     : 6.6.0
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 19 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I included all the necessary information above

**Comment by chuchuva** [comment]
Never mind, somehow my app was using version 5.0.2 of the cordova-plugin-splashscreen plugin even though it had version 5.0.3 in package.json and node_modules\cordova-plugin-splashscreen folder.

**Comment by ravimallya** [comment]
Issue is still there. Mainly I can see the crashes in Oppo, Vivo, Redmi, OnePlus and Samsung Galaxy J series handsets which runs in Android 10 and 9. 
```
	java.lang.NullPointerException: 
	  at org.apache.cordova.splashscreen.SplashScreen$4.run (SplashScreen.java:230)
	  at android.app.Activity.runOnUiThread (Activity.java:6970)
	  at org.apache.cordova.splashscreen.SplashScreen.removeSplashScreen (SplashScreen.java:220)
	  at org.apache.cordova.splashscreen.SplashScreen.access$1000 (SplashScreen.java:50)
	  at org.apache.cordova.splashscreen.SplashScreen$5$1.run (SplashScreen.java:337)
	  at android.os.Handler.handleCallback (Handler.java:883)
	  at android.os.Handler.dispatchMessage (Handler.java:100)
	  at android.os.Looper.loop (Looper.java:224)
	  at android.app.ActivityThread.main (ActivityThread.java:7562)
	  at java.lang.reflect.Method.invoke (Native Method)
	  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
	  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

I'm using target SDK 30 with cordova splash screen 6.0.0. 
![image](https://user-images.githubusercontent.com/2795843/134761251-c9eba649-0dd0-4b69-b468-c1df7c94902d.png)
